// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT).
// See third-party-notices in the repository root for more information.

// Ported from um/xmllite.h in the Windows SDK for Windows 10.0.19041.0
// Original source is Copyright © Microsoft. All rights reserved.

// <auto-generated />
#nullable enable
#pragma warning disable CS0649

namespace TerraFX.Interop
{
    public enum XmlStandalone
    {
        XmlStandalone_Omit = 0,
        XmlStandalone_Yes = 1,
        XmlStandalone_No = 2,
    }
}
